name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: [bug, triage]
assignees:
  - BetaHuhn
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-bug
    attributes:
      label: 🐞 Describe the bug
      description: A clear and concise description of what the bug is
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: 📚 To Reproduce
      description: Steps to reproduce the behavior
      placeholder: Clicked on x and...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: 💡 Expected behavior
      description: A clear and concise description of what you expected to happen
      placeholder: Show ...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: 🖼️ Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Show ...
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output/errors
      description: Please copy and paste any relevant log output/errors. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: dropdown
    id: version
    attributes:
      label: WebCrate Version
      description: What version of WebCrate did the bug occur on (can be found under `?`)
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other